# -*- coding: utf-8 -*-
"""DV-3-4-Spotify-Songs-Collection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxvMmcUwAcI67Pr-Z7CDgQhWpyNOS9Em
"""

import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.express as px

pd.set_option('display.max_columns', None)

df = pd.read_csv("spotify_songs.csv")

# fig1 = px.sunburst(
#     df.groupby(['track_artist', 'track_name']).track_popularity.mean().sort_values(ascending=False).reset_index()[:100],
#     path=['track_artist', 'track_name'],
#     color='track_popularity',
#     #values='track_popularity',
#     labels={'track_popularity': 'Popularity'},
#     title="Artists",
#     height=500,
#     width=1200
# )
#fig1.show()
#in order to manifest the sunburst plot more lucidly, i've opted to show the top 50 rows from the dataset for a magnified visualisation!
sorted_df = df.groupby(['track_artist', 'track_name']).track_popularity.mean().sort_values(ascending=False).reset_index()
num_rows_to_include = 50

fig1 = px.sunburst(
    sorted_df[:num_rows_to_include],
    path=['track_artist', 'track_name'],
    color='track_popularity',
    color_continuous_scale=px.colors.sequential.Redor_r,
    #values='track_popularity',
    title="Artists",
)
fig1.update_layout(height=650, width=1200)
fig1.show()

fig2 = px.parallel_coordinates(pd.concat([df.select_dtypes(float), df.track_popularity], axis=1),
                              color="track_popularity",
                              color_continuous_scale=px.colors.sequential.Sunsetdark_r,
                              color_continuous_midpoint=50,
                               title="Track Popularity",
                               height=500,
                               width=1200)
fig2.show()

df[['playlist_genre', 'playlist_subgenre']] = df[['playlist_genre', 'playlist_subgenre']] \
                                                  .apply(lambda x: x.str.capitalize(), axis=1)
fig3 = px.sunburst(df,
                  path=['playlist_genre', 'playlist_subgenre'],
                  color='track_popularity',
                  color_continuous_scale=px.colors.sequential.Burgyl_r,
                  labels={'track_popularity': 'Popularity'},
                   title="Wheel of Genre Popularity",
                   height=500,
                   width=1200)
fig3.show()
